### ISSUE TITLE
Cleaner replaces question marks with new lines

### ISSUE THREAD

**Issue by cupofjoakim** [trisbee/lingui-locale-cleaner#2]
I don't think this is intended, but maybe your usecase doesn't cover question marks in the translations.

After running `lingui-locale-cleaner locales`, this is the diff I get (apart from the removed usage comment):

```diff
- msgstr "How much will you save?"
+ msgstr "How much will you save
+ "
```

edit: Fixed faulty diff

**Comment by cupofjoakim** [comment]
I take it the regex on [this line](https://github.com/trisbee/lingui-locale-cleaner/blob/master/src/cli.js#L34) is the issue. Running it through rubular we can see that it catches any question mark in a string.

https://rubular.com/r/cBTeidHh17zBmS

**Comment by landsman** [comment]
@cupofjoakim thanks for issue, @HamAndRock will check it.

**Comment by cupofjoakim** [comment]
Solved in #3

**Comment by HamAndRock** [comment]
@cupofjoakim Tag released, please test it.

And thanks a lot.

**Comment by cupofjoakim** [comment]
@HamAndRock Tested and it works! :)
